#!/bin/bash
set -e

DEST=$1
BINARY_NAME="docker-$VERSION"
BINARY_EXTENSION=
if [ "$(go env GOOS)" = 'windows' ]; then
	BINARY_EXTENSION='.exe'
fi
BINARY_FULLNAME="$BINARY_NAME$BINARY_EXTENSION"

# Cygdrive paths don't play well with go build -o.
if [[ "$(uname -s)" == CYGWIN* ]]; then
	DEST=$(cygpath -mw $DEST)
fi

# for libgit2
[ -z "$CGO_CFLAGS" ] && CGO_CFLAGS="-I/go/src/github.com/libgit2/git2go/vendor/libgit2/include"
export CGO_CFLAGS
[ -z "$CGO_LDFLAGS" ] && CGO_LDFLAGS="/go/src/github.com/libgit2/git2go/vendor/libgit2/build/libgit2.a -L/go/src/github.com/libgit2/git2go/vendor/libgit2/build -L/go/src/github.com/libgit2/git2go/vendor/libgit2/install/lib -lrt -lgit2"
export CGO_LDFLAGS

go build \
	-o "$DEST/$BINARY_FULLNAME" \
	"${BUILDFLAGS[@]}" \
	-ldflags "
		$LDFLAGS
		$LDFLAGS_STATIC_DOCKER
	" \
	./docker
echo "Created binary: $DEST/$BINARY_FULLNAME"
ln -sf "$BINARY_FULLNAME" "$DEST/docker$BINARY_EXTENSION"

hash_files "$DEST/$BINARY_FULLNAME"
