#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && rm -rf "$DEST"

(
	export BINARY_SHORT_NAME="$DAEMON_BINARY_NAME"
	export GO_PACKAGE='github.com/docker/docker/cmd/server'
	source "${MAKEDIR}/.binary"
	copy_binaries "$DEST" 'hash'
)
