#!/usr/bin/env bash

set -e
rm -rf "$DEST"

(
	DEST="$(dirname $DEST)/binary-daemon"
	source "${MAKEDIR}/.binary-setup"
	install_binary "${DEST}/${DAEMON_BINARY_NAME}"
	install_binary "${DEST}/${RUNC_BINARY_NAME}"
	install_binary "${DEST}/${CONTAINERD_BINARY_NAME}"
	install_binary "${DEST}/${CONTAINERD_CTR_BINARY_NAME}"
	install_binary "${DEST}/${CONTAINERD_SHIM_BINARY_NAME}"
	install_binary "${DEST}/${PROXY_BINARY_NAME}"
	install_binary "${DEST}/${INIT_BINARY_NAME}"
)
